AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for Deadpool Status Checker

Resources:
  DeadpoolTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Deadpool
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref AWS::StackName

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref DeadpoolTable
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt DeadpoolTable.Arn