AWSTemplateFormatVersion: '2010-09-09'
Description: Update DynamoDB table for Deadpool Status Checker

Resources:
  DeadpoolTableUpdate:
    Type: AWS::DynamoDB::GlobalTable
    Properties:
      TableName: Deadpool
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: SK-PK-index
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Environment
          Value: !Ref AWS::StackName

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref DeadpoolTableUpdate
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt DeadpoolTableUpdate.Arn