version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deadpool-status"
s3_bucket = "deadpool-status"
resolve_s3 = false
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
