version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deadpool-status"
s3_bucket = "deadpool-status"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_prefix = "deadpool-status"
parameter_overrides = "Environment=\"dev\""
