AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AWS Lambda function to check and update person records with Wikipedia data

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Globals:
  Function:
    Runtime: python3.9
    Architectures:
      - x86_64
    Timeout: 300
    MemorySize: 256
    Environment:
      Variables:
        LOG_LEVEL: INFO
        BATCH_SIZE: 50
        TABLE_NAME: Deadpool

Resources:
  DeathNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub deadpool-death-notifications-${Environment}
      DisplayName: "DP"
      Tags:
        - Key: Environment
          Value: !Ref Environment

  DeadpoolStatusChecker:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.9
    Properties:
      CodeUri: ./src
      Handler: lambda_function.lambda_handler
      Description: Checks and updates person records with Wikipedia data
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref DeathNotificationTopic
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Deadpool
        - CloudWatchPutMetricPolicy: {}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt DeathNotificationTopic.TopicName
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
                - sns:CheckIfPhoneNumberIsOptedOut
                - sns:OptInPhoneNumber
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DeleteNetworkInterface
                - ec2:DescribeNetworkInterfaces
              Resource: "*"
      Events:
        DailyCheck:
          Type: Schedule
          Properties:
            Schedule: cron(0 18 * * ? *)
            Name: deadpool-status-daily-check
            Description: Daily check of person records
            Enabled: true
            RetryPolicy:
              MaximumRetryAttempts: 2
      Tags:
        Environment: !Ref Environment

  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DeadpoolStatusChecker}
      RetentionInDays: 30

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref DeadpoolStatusChecker

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt DeadpoolStatusChecker.Arn

  NotificationTopicArn:
    Description: ARN of the SNS notification topic
    Value: !Ref DeathNotificationTopic