AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AWS Lambda function to check and update person records with Wikipedia data

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Globals:
  Function:
    Runtime: python3.9
    Architectures:
      - x86_64
    Timeout: 900
    MemorySize: 256
    Environment:
      Variables:
        LOG_LEVEL: INFO
        BATCH_SIZE: 50
        TABLE_NAME: Deadpool
        MAX_ITEMS_PER_RUN: 500
        AUTO_PAGINATE: true
        MAX_AUTO_INVOCATIONS: 20

Resources:
  DeadpoolStatusChecker:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.9
    Properties:
      CodeUri: ./src
      Handler: lambda_function.lambda_handler
      Description: Checks and updates person records with Wikipedia data
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Deadpool
        - CloudWatchPutMetricPolicy: {}
        - Statement:
            - Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DeleteNetworkInterface
                - ec2:DescribeNetworkInterfaces
              Resource: "*"
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-DeadpoolStatusChecker-*"
      Events:
        DailyCheck:
          Type: Schedule
          Properties:
            Schedule: cron(0 18 * * ? *)
            Name: deadpool-status-daily-check
            Description: Daily check of person records
            Enabled: true
            RetryPolicy:
              MaximumRetryAttempts: 2
      Tags:
        Environment: !Ref Environment

  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DeadpoolStatusChecker}
      RetentionInDays: 30

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref DeadpoolStatusChecker

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt DeadpoolStatusChecker.Arn